### PR TITLE
Add harshdev.thedev.id

### PR DESCRIPTION
**Pull request by harshhhdev**
Just added my name to the list. 

Thanks for making this project, it's really nice :)

### CODE REVIEW

**Comment by Codeize** [comment]
Hey @harshhhdev . Would you prefer harsh.thedev.id as it sounds nicer or woukd you like to continue with harshdev.thedev.id?

**Comment by harshhhdev** [comment]
harsh.thedev.id @Codeize :)

**Comment by Codeize** [comment]
Ok, for verification purposes could you please send a link to your CNAME file in your GitHub Pages Repo? Thanks.

**Comment by harshhhdev** [comment]
I've added it, I think I may have done it wrong though.


I've added the cname.list file, not a link. I didn't get what you meant by that

**Comment by harshhhdev** [comment]
https://github.com/harshhhdev/thedev.id/blob/master/cname.list

**Comment by Codeize** [comment]
Hey @harshhhdev . All you need do is add a file named **exactly** `CNAME` There's no need for a file extension or anything, you don't need the cname.list file either.
Just reply if you're confused and ill help you out :D

**Comment by harshhhdev** [comment]
https://github.com/harshhhdev/harshhhdev.github.io/blob/master/CNAME <- Here it is :)

**Comment by Codeize** [comment]
Hey @harshhhdev. Everything is good so I'll merge this PR and your subdomain will be live within 24 hours, thanks for supporting the project! :D

**Pull request merged**
