### PR TITLE
Update cname.list

### PR DESCRIPTION
**Pull request by Sidohh**

### CODE REVIEW

**Comment by Codeize** [comment]
In the CNAME.list file you spelled it girhub.io. That's incorrect. Please fix it.

**Comment by Sidohh** [comment]
> In the CNAME.list file you spelled it girhub.io. That's incorrect. Please fix it.

fixed it

**Comment by Codeize** [comment]
Hi. Thanks. And can you provide your CNAME file link too please

**Comment by Sidohh** [comment]
> Hi. Thanks. And can you provide your CNAME file link too please

https://github.com/Sidohh/sidohh.github.io/blob/main/CNANE

Here

**Comment by Codeize** [comment]
Done. Your subdomain will be live within 24hrs.

**Pull request merged**
