### PR TITLE
Add dan.thedev.id

### PR DESCRIPTION
**Pull request by dan-unhuman**
my blog which is under development

### CODE REVIEW

**Comment by Codeize** [comment]
Hey @dan-unhuman ! Thanks for the support! Could you please provide a link to your CNAME file in your github repository for verification purposes, thanks.

**Comment by Codeize** [comment]
Hey @dan-unhuman ! Thanks for supporting us! Could you please send a link to your CNAME file for verification purposes? Thanks

**Comment by dan-unhuman** [comment]
> Hey @dan-unhuman ! Thanks for supporting us! Could you please send a link to your CNAME file for verification purposes? Thanks

here the link,, https://blogofdan.netlify.app/CNAME

great job

**Comment by fransallen** [comment]
Hi @dan-unhuman, have you added custom domain `dan.thedev.id` to Netlify?

I did a quick check and it looks like the domain isn't set up on your site yet.

`curl -H "host: dan.thedev.id" https://blogofdan.netlify.app`

```
not found
```

**Comment by dan-unhuman** [comment]
hm,, i'm a bit confuse how/where i should put my CNAME file,, or how i could change mu domain usinh thedev.id in netlify custom domain,,

maybe i'll learn it in a day or two,,

**Comment by Codeize** [comment]
Hey @dan-unhuman ! Have you figured it out yet?

**Comment by dan-unhuman** [comment]
im sorry,, i abort it,, i still dont know,

**Comment by Codeize** [comment]
That's ok! Maybe @fransallen could kindly give you a hand and help figure it out :)

**Comment by Codeize** [comment]
Ok due to this PR being invalid im going to close it. Feel free to start a new PR if you require. Thanks.

**Pull request closed without merging**
