### PR TITLE
Add Raymonzut to cname.list

### PR DESCRIPTION
**Pull request by Raymonzut**

### CODE REVIEW

**Comment by fransallen** [comment]
Thank you for sending a Pull Request, just a question. It looks like you have a premium domain, do you still need thedev.id domain?

**Comment by Raymonzut** [comment]
Thought of including came from the entry by wahyu arief: wahyu.arief.dev; also .dev, a premium domain, which you merged without question in #2

**Comment by fransallen** [comment]
Yeah, I have to contact @wahyuief because the domain is not used yet. @wahyuief do you want me to delete the domain because it is not used?

@Raymonzut can you confirm my question? If you intend to use it, I would be happy to merge

**Comment by Raymonzut** [comment]
@fransallen as i don't intent using it any time soon, i will close this PR for now thus not requesting a merge. Thx for reaching out and this awesome project!

**Pull request closed without merging**
