### PR TITLE
Add wiktor.thedev.id

### PR DESCRIPTION
**Pull request by wiktorwojcik112**
Added my site to cname.list

### CODE REVIEW

**Comment by Codeize** [comment]
Hello @wiktorwojcik112. Thanks for the support, for verification purposes could you please send a link to your CNAME file in your GitHub Pages Repo? Many thanks.

**Comment by wiktorwojcik112** [comment]
This is the link to the CNAME file: https://github.com/wiktorwojcik112/wiktorwojcik112.github.io/blob/main/CNAME. Thank you for domain.

**Comment by Codeize** [comment]
Ok @wiktorwojcik112, I will add that subdomain and it should be active within 24 hours. Many thanks for the support!

**Comment by wiktorwojcik112** [comment]
It works. Thank you.

**Pull request merged**
