### PR TITLE
add adryzz.thedev.id

### PR DESCRIPTION
**Pull request by adryzz**

### CODE REVIEW

**Comment by adryzz** [comment]
sorry my bad

**Comment by Codeize** [comment]
Hey @adryzz . Thanks for the support! For verification purposes could you please send a link to your CNAME file in your GitHub Pages website? Thanks.

**Comment by adryzz** [comment]
https://github.com/adryzz/adryzz.github.io/blob/master/CNAME

**Comment by Codeize** [comment]
Alrighty. Thanks so much @adryzz for the support, I'll merge this PR right now and your subdomain should be active within 24 hours. Thanks. :)

**Pull request merged**
