### PR TITLE
add demonkingswarn.thedev.id

### PR DESCRIPTION
**Pull request by DemonKingSwarn**
DemonKingSwarn: demonkingswarn.github.io

### CODE REVIEW

**Comment by Codeize** [comment]
Hello, please send a link to your CNAME file for verification. And arrange the cname.list commit in alphabetical order.

**Comment by DemonKingSwarn** [comment]
> Hello, please send a link to your CNAME file for verification. And arrange the cname.list commit in alphabetical order.

https://github.com/DemonKingSwarn/DemonKingSwarn.github.io/blob/main/CNAME 
Sorry for late reply ;-;

**Comment by Codeize** [comment]
Hey, sorry to be fussy but its better for us if its alphabetically ordered.  _M comes before N_
If you just re commit with that quick change we'll be good to go. Thanks :)

**Comment by DemonKingSwarn** [comment]
> Hey, sorry to be fussy but its better for us if its alphabetically ordered. _M comes before N_
> If you just re commit with that quick change we'll be good to go. Thanks :)

done :)

**Comment by DemonKingSwarn** [comment]
> > Hey, sorry to be fussy but its better for us if its alphabetically ordered. _M comes before N_
> > If you just re commit with that quick change we'll be good to go. Thanks :)
> 
> done :)

http://demonkingswarn.thedev.id/ is not working

**Comment by Codeize** [comment]
1st. You didn't commit that change.
2nd. The subdomain won't be activated until you complete all the steps.
3rd. Once you recommit with the cname.list file fixed, provide a link to your CNAME file in your GitHub Pages Repo.
Thanks :)

**Pull request closed without merging**
