### PR TITLE
Update subdomains.json

### PR DESCRIPTION
**Pull request by Rahuletto**

### CODE REVIEW

**Comment by Rahuletto** [comment]
Seems like the repo is inactive

**Comment by lakuapik** [comment]
@Rahuletto hi there, sorry for the late response. at the time, thedev.id maintainer was busy. would you still want the subdomain? i can help you set it up. thanks.

**Comment by Rahuletto** [comment]
Yea sure 😳

**Comment by lakuapik** [comment]
@Rahuletto great!

This pull request cannot be opened again, you've deleted the branch, so please open new PR, i will proceed.

**Comment by Rahuletto** [comment]
#507

**Pull request closed without merging**
