### PR TITLE
Add piyush.thedev.id

### PR DESCRIPTION
**Pull request by officialpiyush**

### CODE REVIEW

**Comment by Codeize** [comment]
Can you please send a link to your CNAME file in your GitHub Pages Repo for verification purposes. Thanks

**Comment by officialpiyush** [comment]
https://github.com/officialpiyush/piyush.thedev.id/blob/main/CNAME - Here, but you can't see it, it's a private repository. Here is a screenshot:
image

**Comment by Codeize** [comment]
Hey @officialpiyush. Unfortunately it can't be private, please set it public.

**Comment by officialpiyush** [comment]
Ah, I see, I'll make another repo then :p

**Comment by Codeize** [comment]
You could just make it public, but whatever works for you! :)

**Comment by officialpiyush** [comment]
https://github.com/officialpiyush/linkyard/blob/main/CNAME there you go

**Comment by Codeize** [comment]
Hey @officialpiyush 
I'm confused as to how you're hosting that new website? Is it online now?

**Comment by officialpiyush** [comment]
CNAME hasn't been updated by your side, so no, the website isn't online atm - https://officialpiyush.github.io/linkyard

**Comment by Codeize** [comment]
So the website is officialpiyush.github.io/linkyard. 
And you want that URL to be piyush.thedev.id.
Correct?

**Comment by officialpiyush** [comment]
Yeah

**Comment by Codeize** [comment]
Alright, sorry for the confusion. I'll get this sorted. Thanks!

**Comment by Codeize** [comment]
Hey, @officialpiyush . Unfortunately this isn't possible. Please use a domain that isn't a page.

**Comment by officialpiyush** [comment]
ig you're hella confused lol.

1. The repo is public
2. The website isn't live because I have a **CNAME** file in the repo which points to `piyush.thedev.id` whose DNS record hasn't been set.

lmk if you want me to link you to the github guide about CNAMEs :)

**Comment by Codeize** [comment]
@officialpiyush , I wont be needing that guide, I've worked with website and website hosting for a long time. 

Its impossible to point the subdomain to a page (linkyard). It has to point to a root domain. That isn't our fault, that's the way website CNAMEs work. 

Please either reply with the **root** domain you would like to use. Or else I'll close the PR.
Sorry for any inconvenience caused. 

Note : I've just noticed you have a premium domain already, so it doesn't make much sense get a subdomain when you have a premium one. Thanks.

**Comment by Codeize** [comment]
@officialpiyush , I wont be needing that guide, I've worked with website and website hosting for a long time. :)

Its impossible to point the subdomain to a page (linkyard). It has to point to a root domain. That isn't our fault, that's the way website CNAMEs work. 

Please either reply with the **root** domain you would like to use. Or else I'll close the PR.
Sorry for any inconvenience caused. 

Note : I've just noticed you have a premium domain already, so it doesn't make much sense get a subdomain when you have a premium one. Thanks.

**Comment by officialpiyush** [comment]
1. I believe that getting a subdomain of `thedev.id` is a personal choice for now ( if not then my bad, you can close this PR ) plus my domain will be expiring this month lol
2. I don't know why pointing it to `officialpiyush.github.io` wouldn't work. For example here is a sub-domain I just created - https://sample.piyush.codes/, it's repo - https://github.com/officialpiyush/sample having a CNAME record pointing to `officialpiyush.github.io`
image This is how CNAMEs work
3. Sorry if my previous comment offended you.

If this is not what you are talking about then it might be I'm looking in the wrong direction, if so, please get me in the right direction :p

**Comment by Codeize** [comment]
Hey @officialpiyush . You caused no offense, don't worry about it :)

Unfortunately you are able to set the subdomain as its your website, its different on our end. 

So you're wanting officialpiyush.github.io to be piyush.thedev.id?
In doing so you will need to remove your premium domain from pointing to your website.

If that's what you want to do lmk and we can (finally) close this PR :) 
Many thanks.

**Comment by officialpiyush** [comment]
The thing is, idk why it won't work, if you tell me how it's on your end I can try to explain it, I have my gametracker.js docs hosted on js.org, their subdomain points to officialpiyush.github.io. Also if you think it's because I used it on piyush.codes domain, here I have it on piyushdev.ml now - https://sample.piyushdev.ml/ ( the same CNAME record ). 

This is how custom domains on github work:
- You add a subdomain on the repository you want
- You go to the DNS zone of the website and add a CNAME record for the subdomain pointing to the premium domain ( if any ) **OR** `<username>.github.io` ( any of em' works )
- You visit that subdomain and boom it's live :p

I don't understand why mine won't work.
Again here are the details of the domain I need

**Domain:** `piyush.thedev.id`
**CNAME:** `officialpiyush.github.io`

**Comment by officialpiyush** [comment]
@Codeize ^

**Comment by Codeize** [comment]
Thats what I'm asking. I'll get it done.

**Comment by Codeize** [comment]
All done. Your subdomain is live. Thanks.

**Comment by officialpiyush** [comment]
Thanks for the subdomain and putting up with me lol 💜

**Comment by officialpiyush** [comment]
is it okay if I change it to a netlify domain now  😅? I can use a private repo then 🌚

**Comment by Codeize** [comment]
Change the custom domain then. 
Are you totally sure because I can't go around changing the CNAMEs for fun.
Get back to me :)

**Pull request merged**
