### PR TITLE
Update cname.list

### PR DESCRIPTION
**Pull request by yeetedmeme**
Personal Portfolio And Projects
[CNAME link](https://github.com/yeetedmeme/ash-hnry/blob/main/CNAME)
yeetedmeme.github.io/ash-hnry

### CODE REVIEW

**Comment by Codeize** [comment]
Hey! @yeetedmeme . Unfortunately our systems don't facilitate subdomains for specific pages. Only root domains or subdomains. So basically please provide a root domain and we'll be happy to continue. Thanks!

**Comment by yeetedmeme** [comment]
Does [this](https://ash-hnry.github.io) work? I made an organization so it should work as a root domain
[CNAME Link](https://github.com/ash-hnry/ash-hnry.github.io/blob/master/CNAME)

**Comment by Codeize** [comment]
Yep that'll work. Just recommit with the updated cname.list and we'll be good to go.:)

**Comment by yeetedmeme** [comment]
Added!

**Comment by Codeize** [comment]
Ok. I'll get this PR merged and your subdomain will be active soon. Thanks!

**Comment by yeetedmeme** [comment]
thanks!

**Pull request merged**
