### PR TITLE
Add bd103.thedev.id

### PR DESCRIPTION
**Pull request by BD103**
Thanks for doing this! :)

### CODE REVIEW

**Comment by Codeize** [comment]
Hi. Can you please provide a link to your CNAME file?

**Comment by BD103** [comment]
Just did. :P

**Comment by Codeize** [comment]
No, please provide an actual link to the repo with the CNAME file.

**Comment by BD103** [comment]
Oh. I'm sorry for not understanding. [Here.](https://github.com/BD103/bd103.github.io/blob/main/docs/CNAME)

**Comment by Codeize** [comment]
Your subdomain will be live within 24 hours.

**Pull request merged**
