### PR TITLE
Update cname.list

### PR DESCRIPTION
**Pull request by Crispy-Cream**
Adding crispy.thedev.id

[CNAME](https://github.com/Crispy-Cream/Crispy/blob/main/CNAME)

### CODE REVIEW

**Comment by Codeize** [comment]
Hi. We can't provide subdomains for pages. Would you like it linked to the root site instead?

**Comment by Crispy-Cream** [comment]
> Hi. We can't provide subdomains for pages. Would you like it linked to the root site instead?

Sure that's fine, if you can change the cname and add it i'll fix it on my side as well. Thanks!

**Comment by Codeize** [comment]
You'll have to recommit with the updated cname file

**Comment by Crispy-Cream** [comment]
> You'll have to recommit with the updated cname file

Updated it, should be all good to go.

**Comment by Crispy-Cream** [comment]
New CNAME is [here](https://github.com/Crispy-Cream/crispy-cream.github.io/blob/main/CNAME)

**Comment by Codeize** [comment]
And can you please provide the CNAME link in that sites repo.

**Comment by Codeize** [comment]
Sorry I missed it, thanks.

**Comment by Crispy-Cream** [comment]
> Sorry I missed it, thanks.

No problem! Do you know how long it will take for me to get my domain?

**Comment by Codeize** [comment]
Hello. Your subdomain will be live within 24 hours. Thanks!

**Pull request merged**
