### PR TITLE
Update cname.list

### PR DESCRIPTION
**Pull request by CozmoDev**

### CODE REVIEW

**Comment by Codeize** [comment]
Hey! Please provide your CNAME link.

**Comment by CozmoDev** [comment]
> Hey! Please provide your CNAME link.

What do you mean CNAME link?

**Comment by Codeize** [comment]
The link to the CNAME file in your GitHub Repo :)

**Comment by CozmoDev** [comment]
> The link to the CNAME file in your GitHub Repo :)

Could you please respond?

**Comment by Codeize** [comment]
Hello. Sorry for the wait, the CNAME link appears to be invalid.

**Comment by CozmoDev** [comment]
I have put the custom domain again , it should now be valid.

**Comment by Codeize** [comment]
Alright all seems good. I'll merge this and your subdomain will be live within 24hrs. Thanks!

**Comment by Codeize** [comment]
Wait, one last thing. Can you re commit and add your cname.list record in **alphabetical** order please.

**Comment by CozmoDev** [comment]
Done

**Comment by Codeize** [comment]
Thanks. Enjoy the subdomain!

**Pull request merged**
