### PR TITLE
add skidee.thedev.id

### PR DESCRIPTION
**Pull request by HeySkidee**

### CODE REVIEW

**Comment by Codeize** [comment]
CNAME link please?

**Comment by HeySkidee** [comment]
> CNAME link please?

http://skidee.thedev.id

**Comment by Codeize** [comment]
That isn't your CNAME file. The actual link to your cmame file in your repo.

**Comment by HeySkidee** [comment]
> That isn't your CNAME file. The actual link to your cmame file in your repo.

oh sorry my bad 😅
there: https://github.com/HeySkidee/HeySkidee.github.io/blob/master/CNAME

**Pull request closed without merging**
