### PR TITLE
Update subdomains.json

### PR DESCRIPTION
**Pull request by TajuModding**
Tried replit domain lets see if it works or not!

### CODE REVIEW

**Comment by fransallen** [comment]
Hmm, `api` is a common name used for internal system. Can you pick another name?

**Comment by TajuModding** [comment]
actually making an api none used it so umm can u a request?

**Comment by TajuModding** [comment]
okh updated will `randomapi` be fine?

**Comment by fransallen** [comment]
I'm afraid this might have conflicts in the future, please use thedev.id for a personal domain only (dev blog, portofolio, etc), not a service (i.e API). An example of correct usage is `yourname.thedev.id`, and not `someservice.thedev.id`. thedev.id is a free service, but the project doesn't seem suitable for your current interest.

**Pull request closed without merging**
