### PR TITLE
ahskript.thedev.id

### PR DESCRIPTION
**Pull request by ahSkript**

### CODE REVIEW

**Comment by Codeize** [comment]
Please link your CNAME file.

**Comment by ahSkript** [comment]
CNAME link : [https://github.com/ahSkript/ahskript.github.io/blob/main/CNAME](https://github.com/ahSkript/ahskript.github.io/blob/main/CNAME)

**Comment by Codeize** [comment]
Merged! Your subdomain will be live within 24 hours.

**Comment by Codeize** [comment]
Update: please resolve the conflicts and this will be merged!

**Comment by Codeize** [comment]
Thanks!

**Pull request merged**
