### PR TITLE
Update cname.list

### PR DESCRIPTION
**Pull request by ezedinff**
i have added mine to the list :)

### CODE REVIEW

**Comment by Codeize** [comment]
Please provide a CNAME link.

**Comment by ezedinff** [comment]
this is a link for the CNAME
https://github.com/ezedinff/thedev.id/blob/master/cname.list

**Comment by ezedinff** [comment]
dendydharmawan.thedev.id is did same thing. he doesn't provide CNAME
check his pull request. https://github.com/fransallen/thedev.id/pull/11

**Comment by ezedinff** [comment]
what happened?

**Comment by Codeize** [comment]
I see you are now hosting on Vercel, as a result you can delete the CNAME file and add the subdomain via your Vercel dashboard.

**Comment by ezedinff** [comment]
this is the error i got from vercel dashboard while i'm trying to add subdomain.


The domain ezedin.thedev.id is already owned by another Vercel account.

**Comment by Codeize** [comment]
Hmmm. It seems like an error. I'm not too sure if it'll work. So I'm gonna have to close this PR. If you resolve it please start another PR. Sorry.

**Pull request closed without merging**
