### PR TITLE
Add fivenine.thedev.id

### PR DESCRIPTION
**Pull request by fivenine01**

### CODE REVIEW

**Comment by Codeize** [comment]
Hey @fivenine01! Thanks for the support.
For verification purposes can you please comment back with a link to your CNAME file in your github pages repository? Thanks, Code.

**Comment by fivenine01** [comment]
https://github.com/fivenine01/fivenine01.github.io/CNAME

**Comment by Codeize** [comment]
Hmm, that link doesn't exist, I think you sent the wrong link..

**Comment by fivenine01** [comment]
sorry for that
https://www.github.com/fivenine01/fivenine01.github.io/tree/master/CNAME

**Comment by Codeize** [comment]
Ok! Everything seems good, I'll merge that for you @fivenine01 and @fransallen will add the subdomain, please be aware that this process can take up to 24 hours for your subdomain to be active so please be patient. Thanks for supporting thedev.id :D

**Pull request merged**
