### PR TITLE
Add anamolsapkota.thedev.id

### PR DESCRIPTION
**Pull request by anamolsapkota**

### CODE REVIEW

**Comment by Codeize** [comment]
Hi please provide a link to your repo with the CNAME file.

**Comment by anamolsapkota** [comment]
> Hi please provide a link to your repo with the CNAME file.

https://github.com/anamolsapkota/anamolsapkota.thedev.id

**Comment by Codeize** [comment]
Hi, your github pages site isn't even live.

**Comment by anamolsapkota** [comment]
> Hi, your github pages site isn't even live.

I had added "anamolsapkota.thedev.id" as the custom domain. 
It is now working: https://anamolsapkota.github.io/anamolsapkota.thedev.id/

**Comment by TheBotlyNoob** [comment]
Please develop the website at https://anamolsapkota.github.io/, or https://github.com/anamolsapkota/anamolsapkota.github.io. Or else your changes wont show up at the domain!

**Comment by anamolsapkota** [comment]
> Please develop the website at https://anamolsapkota.github.io/, or https://github.com/anamolsapkota/anamolsapkota.github.io. Or else your changes wont show up at the domain!

I have now created at: https://github.com/anamolsapkota/anamolsapkota.github.io
Thanks!

**Comment by TheBotlyNoob** [comment]
you should also check `enforce https`

**Comment by anamolsapkota** [comment]
> you should also check `enforce https`

I could not do that as it is giving me an error: "anamolsapkota.thedev.io is improperly configured
Your site's DNS settings are using a custom subdomain, anamolsapkota.thedev.io, that's set up as an A record. We recommend you change this to a CNAME record pointing at [YOUR USERNAME].github.io. For more information, see Learn more (InvalidARecordError). We recommend you change this to a CNAME record pointing to anamolsapkota.github.io."

**Comment by TheBotlyNoob** [comment]
> > you should also check `enforce https`
> 
> I could not do that as it is giving me an error: "anamolsapkota.thedev.id is improperly configured
> Domain's DNS record could not be retrieved. For more information, see Learn more (InvalidDNSError). We recommend you change this to a CNAME record pointing to anamolsapkota.github.io."

We have not merged this yet, as I am just a helper we have to wait for @Codeize

**Comment by Codeize** [comment]
Your subdomain will be live within 24 hours.

**Pull request merged**
