### PR TITLE
Add goose.thedev.id

### PR DESCRIPTION
**Pull request by scalgoon**

### CODE REVIEW

**Comment by Codeize** [comment]
Hey @scalgoon ! Thanks for supporting thedev.id. Could you please send a link to your CNAME file in your repository for verification purposes. Thanks, Code.

**Comment by scalgoon** [comment]
> Hey @scalgoon ! Thanks for supporting thedev.id. Could you please send a link to your CNAME file in your repository for verification purposes. Thanks, Code.

here ya go https://github.com/scalgoon/scalgoon.github.io/blob/main/CNAME

**Comment by Codeize** [comment]
Ok, @scalgoon, I've merged this and @fransallen will add the subdomain soon. Thanks for the support!
This process can take 24 hours or more so please be patient. Thanks, Code

**Comment by fransallen** [comment]
Hi @scalgoon, please correct your CNAME file, you can see the [documentation here](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site), I'll activate the domain once this issue is resolved.

Also, the subdomain are not placed in alphabetical order, this will cause some hassle in the future if not resolved, @Codeize would you mind checking this too next time? That'd be amazing

**Comment by scalgoon** [comment]
> Hi @scalgoon, please correct your CNAME file, you can see the [documentation here](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site), I'll activate the domain once this issue is resolved.
> 
> Also, the subdomain are not placed in alphabetical order, this will cause some hassle in the future if not resolved, @Codeize would you check that too before merging, next time? That'd be amazing

Hi @fransallen I got the CNAME file updated here is the link to it https://github.com/scalgoon/scalgoon.github.io/blob/main/CNAME

**Comment by fransallen** [comment]
Ok, domain is now activated :tada:

**Pull request merged**
