### PR TITLE
Update subdomains.json

### PR DESCRIPTION
**Pull request by TajuModding**
added my domain

### CODE REVIEW

**Comment by fransallen** [comment]
Can you sort alphabetically?

**Comment by TajuModding** [comment]
am on phone currently can u do on my behalf.. :)

**Comment by TajuModding** [comment]
arranged alphabetically

**Comment by fransallen** [comment]
> am on phone currently can u do on my behalf.. :)

> arranged alphabetically

I would, but since you've done it before me, merged.

**Pull request merged**
