### PR TITLE
Update cname.list

### PR DESCRIPTION
**Pull request by DemonKingSwarn**

### CODE REVIEW

**Comment by Codeize** [comment]
Hi. Could you please change the cname.list file, m comes before n. Also provide a link to your website's CNAME file. 
Thanks!

**Comment by DemonKingSwarn** [comment]
https://github.com/DemonKingSwarn/demonkingswarn.github.io/blob/main/CNAME

**Comment by Codeize** [comment]
Hi, could you correct the cname.list with a commit to this PR. Thanks.

**Comment by Codeize** [comment]
Closed due to inactivity.

**Pull request closed without merging**
