### PR TITLE
Add jj.thedev.id

### PR DESCRIPTION
**Pull request by TheBotlyNoob**
[CNAME link](https://github.com/TheBotlyNoob/TheBotlyNoob.github.io/blob/main/CNAME)

### CODE REVIEW

**Comment by Codeize** [comment]
Hi. Please provide a CNAME link to your repo.

**Comment by TheBotlyNoob** [comment]
ok done...

**Comment by Codeize** [comment]
You sent no link..

**Comment by TheBotlyNoob** [comment]
i dont understand...

**Comment by TheBotlyNoob** [comment]
nvm its [here](https://github.com/TheBotlyNoob/TheBotlyNoob.github.io/blob/main/CNAME)

**Comment by Codeize** [comment]
Alright. <b>Your subdomain will be live within 24hrs</b> :)

**Comment by TheBotlyNoob** [comment]
:)

**Comment by TheBotlyNoob** [comment]
its already live :)

**Comment by Codeize** [comment]
We are next level speed ;)

**Comment by TheBotlyNoob** [comment]
yes

**Pull request merged**
