### PR TITLE
Add trungbot.thedev.id

### PR DESCRIPTION
**Pull request by TrungDo2309**
SO many thanks for the team for creating this nifty, free way of making website domains for developers! It's amazing nowadays when you can connect with many people around the world to create such massive projects.

### CODE REVIEW

**Comment by Codeize** [comment]
Thanks for supporting Trung :D

**Comment by Codeize** [comment]
Thanks for supporting thedev.id, Trung :D

**Comment by fransallen** [comment]
Hi @TrungDo2309 before we merge the PR, would you create a CNAME to your GitHub Pages and send the link here for verification?

**Comment by Codeize** [comment]
Ok, @TrungDo2309, PR was merged, your subdomain will be added soon and should be active within 24hours, thanks!

**Pull request merged**
