### PR TITLE
anon.thedev.id

### PR DESCRIPTION
**Pull request by anondev-sudo**

### CODE REVIEW

**Comment by anondev-sudo** [comment]
Why I can't add it? 
image

**Comment by fransallen** [comment]
This is a known issue. While we are working to add thedev.id as a Public Suffix, you can use the thedev.id subdomain for your GitHub Pages.

**Comment by anondev-sudo** [comment]
Netlify is being annoying with that you can't use add subdomains when another subdomain is owned by someone else.

**Comment by fransallen** [comment]
I'm sure it's for security purpose. I'll see what I can do from this side.

For now, if you wish to use thedev.id subdomain, you can use GitHub Pages.

**Comment by anondev-sudo** [comment]
Inform me when it will be possible to use Vercel or Netlify

**Pull request closed without merging**
