### PR TITLE
Add rikiadisetiawan: rikiadisetiawan.github.io

### PR DESCRIPTION
**Pull request by rikiadisetiawan**

### CODE REVIEW

**Comment by Codeize** [comment]
We don't support Netlify. Please use GH Pages or Vercel. Thanks.

**Comment by rikiadisetiawan** [comment]
done, just moved my site to github. Thanks! 👋

**Comment by Codeize** [comment]
Hey @rikiadisetiawan. Your website isn't live. This could be because your repo is set to private.

**Comment by rikiadisetiawan** [comment]
nope, i already set to public, you can check the link here and it's live already :
https://rikiadisetiawan.github.io/freshydigital.github.io/

**Comment by Codeize** [comment]
We don't support pages, root domains only please :)

**Comment by aalfiann** [comment]
@rikiadisetiawan , your website must be accessible through this >>https://freshydigital.github.io

**Not like this** >> https://rikiadisetiawan.github.io/freshydigital.github.io

**Comment by rikiadisetiawan** [comment]
@aalfiann ah thank. it's fixed now.

**Comment by aalfiann** [comment]
No, it's not fixed yet.. Have you try to open this url https://freshydigital.github.io at your browser?

Because I've seen this as 404 not found.

**Comment by rikiadisetiawan** [comment]
> 
> 
> No, it's not fixed yet.. Have you try to open this url https://freshydigital.github.io at your browser?
> 
> Because I've seen this as 404 not found.

@aalfiann oh its https://rikiadisetiawan.github.io ,i was supposed to use the root domain right?

**Comment by Codeize** [comment]
@rikiadisetiawan hi. Whats the name you are asking for the subdomain?

**Comment by rikiadisetiawan** [comment]
It's  freshy.thedev.id  , i already create the CNAME file on my page as my custom domain. Thank you! @Codeize

**Comment by Codeize** [comment]
Hey, please re-commit with the updated cname.list file to reflect the changes as the cname.list doesn't reflect the name you want :)

**Comment by Codeize** [comment]
Closed for inactivity.

**Pull request closed without merging**
