### PR TITLE
Add subtra3t.thedev.id

### PR DESCRIPTION
**Pull request by subtra3t**

### CODE REVIEW

**Comment by Codeize** [comment]
Hi. Please link the CNAME file.

**Comment by subtra3t** [comment]
> Hi. Please link the CNAME file.

What do you mean?

**Comment by Codeize** [comment]
Hi. Please link the CNAME file in your GitHub Pages Repo.

**Comment by subtra3t** [comment]
> Hi. Please link the CNAME file in your GitHub Pages Repo.

I have done that.

**Comment by Codeize** [comment]
No. Please provide an actual link to the file.

**Comment by Codeize** [comment]
Take the other merged PRs as examples.

**Comment by subtra3t** [comment]
Oh, then I think you meant [this](https://github.com/subtra3t/subtra3t.github.io/blob/master/CNAME)

**Comment by Codeize** [comment]
Yep that's the link. Just please remove the https://

**Comment by subtra3t** [comment]
> Yep that's the link. Just please remove the https://

Okay.

**Comment by Codeize** [comment]
Alright, I'm gonna merge this PR and your subdomain will be live within 24hrs. Thanks!

**Comment by subtra3t** [comment]
Hi. I think something went wrong with the subdomain: 
image

Did I do something wrong?

**Pull request merged**
