### PR TITLE
Add jefrydco to cname.list

### PR DESCRIPTION
**Pull request by jefrydco**

### CODE REVIEW

**Comment by fransallen** [comment]
Hi @jefrydco,

Merged :link: 

Don't forget to add `jefrydco.thedev.id` to your Netlify account. Please note that the domain must not be used as a redirect or it can be deleted from the record.

**Comment by jefrydco** [comment]
Hi @fransallen  ,

Thanks for merging my PR. I'm sorry I don't know that there is a term stated it can't be used as a redirect. Perhaps you create some notice on the readme section or on the website regarding of that. In the meantime, I'll soon create another PR to delete the record.

Anyway is there any chance you could create perhaps some blog post how this thing work behind the scenes, I would very happy to read it thoroughly :smile:

**Comment by fransallen** [comment]
Of course! I will add a notice. Thanks for your suggestion.

The reason redirects are not permitted is that there is no benefit in using **thedev.id** for this kind of use. It can be said this domain is perfect for personal websites for developers who don't want to be tied to domain purchases.

**Comment by fransallen** [comment]
For blog posts, maybe I'll add some on the [forum](https://statically.discourse.group).

**Pull request merged**
