### PR TITLE
Add codeize.thedev.id

### PR DESCRIPTION
**Pull request by Codeize**

### CODE REVIEW

**Comment by Codeize** [comment]
Updated CNAME List, added subdomain.

**Comment by fransallen** [comment]
Hi @Codeize, thanks for submitting the PR.

Since the subdomain `code` is likely to cause confusion in the future, would you like to use `codeize` instead?

**Comment by Codeize** [comment]
Yea sure. Thanks so much dude 🙏

**Comment by Codeize** [comment]
@fransallen

**Comment by fransallen** [comment]
Awesome! You are good to go now.

**Comment by Codeize** [comment]
@fransallen I hope this is ok. Thanks!

**Comment by Codeize** [comment]
Hey @fransallen, when I try redirect my vercel.app domain to my dev.id domain it says it’s already in use by another Vercel user, this must be you, I’m new to Vercel so is there any workaround for this? If not thanks.

**Pull request merged**
